version: 0.2

phases:
  install:
    commands:
      - python3 -m venv /opt/citools
      - /opt/citools/bin/pip install --upgrade pip setuptools wheel
      - /opt/citools/bin/pip install cfn-lint taskcat
  build:
    commands:
      - /opt/citools/bin/cfn-lint cloudformation/root.yaml cloudformation/modules/*.yaml pipeline/codepipeline.yaml --ignore-checks W3002
      - /opt/citools/bin/taskcat test run

artifacts:
  files:
    - "**/*"
